# Generated by Django 2.2.5 on 2019-09-22 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('member_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=10, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('leader', models.CharField(default=None, max_length=50, verbose_name='Lider')),
                ('department', models.CharField(default=None, max_length=30, verbose_name='Area')),
                ('post', models.CharField(max_length=30, verbose_name='Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
